nelmio_api_doc:
    documentation:
        info:
            title: APIQUIZ
            description: Bienvenue sur APIQUIZ, une API de génération aléatoire de Quiz
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
